### ISSUE TITLE
AAR_KV constant

### ISSUE THREAD

**Issue by zsolt2255** [Vauff/AdvancedAutoRetry-Workers#1]
Hi, 

the AAR_KV constant is missing.

```
ReferenceError: AAR_KV is not defined
    at handleRequest (worker.js:24:16)
    at worker.js:3:5
```

**Comment by Vauff** [comment]
You first need to setup a KeyValues namespace in the KV section of the workers dashboard.
![image](https://user-images.githubusercontent.com/6075172/124203025-c6870e00-daa9-11eb-9f54-8aa19e62e578.png)

AAR_KV then refers to that KeyValues namespace binded in the settings of the workers like so.
![image](https://user-images.githubusercontent.com/6075172/124202722-ff72b300-daa8-11eb-9f29-6265d5e95ff2.png)

**Comment by zsolt2255** [comment]
Okay, thanks for the help, now I'm getting the following response back:

```
{
"clientDownloaded": value (true or false)
}
```
